/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './views/**/*.php',
    './views/**/*.php.deploy',
    './public/**/*.php',
    './public/**/*.php.deploy',
    './public/assets/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#17721c',
        outline: '#757683',
        'on-primary-fixed-variant': '#274093',
        'tertiary-fixed-dim': '#ffb872',
        tertiary: '#6b3c00',
        'surface-dim': '#dcd9d9',
        'accent-sky': '#00B0FF',
        'surface-tint': '#4159ac',
        'surface-container-highest': '#e4e2e1',
        background: '#fbf9f8',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'status-cancelled': '#D32F2F',
        'status-progress': '#FFBF00',
        'status-completed': '#30872F',
        'on-surface': '#1b1c1c',
        'accent-magenta': '#D81B60',
        'on-error': '#ffffff',
        'on-surface-variant': '#444651',
        'on-secondary': '#ffffff',
        'surface-variant': '#e4e2e1',
        'tertiary-container': '#8d5100',
        'surface-gray': '#F5F5F5',
        'status-certified': '#D4AF37',
        'inverse-surface': '#303030',
        'primary-container': '#425aad',
        'secondary-container': '#9af58e',
        error: '#ba1a1a',
        'status-announced': '#425AAD',
        'outline-variant': '#c5c5d3',
        'inverse-primary': '#b6c4ff',
        'status-draft': '#9E9E9E',
        'on-primary-fixed': '#001550',
        'on-tertiary-fixed-variant': '#6a3c00',
        'on-tertiary-container': '#ffd2aa',
        'tertiary-fixed': '#ffdcbf',
        secondary: '#106e18',
        'accent-yellow': '#FFD600',
        'on-background': '#1b1c1c',
        'surface-bright': '#fbf9f8',
        'on-secondary-fixed': '#002202',
        'surface-container': '#f0eded',
        'on-primary': '#ffffff',
        surface: '#fbf9f8',
        'inverse-on-surface': '#f3f0f0',
        'on-tertiary-fixed': '#2d1600',
        'status-scheduled': '#008080',
        'primary-fixed-dim': '#b6c4ff',
        'on-error-container': '#93000a',
        'surface-container-low': '#f6f3f2',
        'accent-coral': '#FF7043',
        'on-primary-container': '#d1d8ff',
        'secondary-fixed': '#9df891',
        'primary-fixed': '#dce1ff',
        primary: '#284194',
        'on-secondary-fixed-variant': '#00530b',
        'secondary-fixed-dim': '#82db77',
        'error-container': '#ffdad6',
        'surface-container-high': '#eae8e7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit-xs': '4px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'unit-lg': '24px',
        'unit-xl': '48px',
        'unit-md': '16px',
        'margin-desktop': '40px',
        gutter: '24px',
        'unit-sm': '8px',
      },
      maxWidth: {
        '1280px': '1280px',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['IBM Plex Sans', 'sans-serif'],
        'headline-md': ['IBM Plex Sans', 'sans-serif'],
        'headline-lg': ['IBM Plex Sans', 'sans-serif'],
        'headline-sm': ['IBM Plex Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['IBM Plex Sans', 'sans-serif'],
        heading: ['IBM Plex Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        arabic: ['Cairo', 'sans-serif'],
        cairo: ['Cairo', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        card: '0px 4px 12px rgba(0, 0, 0, 0.05)',
        overlay: '0px 8px 24px rgba(0, 0, 0, 0.12)',
        glow: '0 0 40px rgba(66, 90, 173, 0.25)',
        lift: '0 20px 40px rgba(40, 65, 148, 0.15)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'mesh-drift': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(2%, -2%) scale(1.05)' },
          '66%': { transform: 'translate(-2%, 2%) scale(0.98)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'fade-in': 'fade-in 0.5s ease-out forwards',
        float: 'float 6s ease-in-out infinite',
        'mesh-drift': 'mesh-drift 18s ease-in-out infinite',
        shimmer: 'shimmer 2s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};